name: Test Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0' # Assurez-vous que cette version est correcte

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Exécution des tests
      - name: Run tests
        run: npm test
